# Generated by Django 4.2.16 on 2024-11-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='disc',
            field=models.TextField(default='ammm'),
            preserve_default=False,
        ),
    ]
