# Generated by Django 4.2.16 on 2024-10-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/')),
                ('topic', models.CharField(max_length=200)),
                ('disc', models.TextField()),
            ],
        ),
    ]
