# Generated by Django 4.2.16 on 2024-10-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
