# Generated by Django 4.2.16 on 2024-10-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exploreKits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_name', models.CharField(max_length=100)),
                ('Img', models.ImageField(upload_to='photot/')),
                ('starting_price', models.FloatField()),
                ('Ending_price', models.FloatField()),
                ('about_kit', models.TextField()),
            ],
        ),
    ]
